version: '3.7'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 2.7.0
        APP_PATH: /approot
        RAILS_ENV: production
    env_file: .env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/approot:cached
      - ./log:/approot/log:cached
      - tmp-volume:/approot/tmp
    tty: true
    stdin_open: true
    restart: always
  web:
    build:
      context: containers/nginx
    volumes:
      - public-volume:/approot/public
      - tmp-volume:/approot/tmp
    ports:
      - 80:80
    depends_on:
      - app
    restart: always
  terraform:
    image: hashicorp/terraform:0.12.20
    volumes:
      - ./terraform:/terraformroot
    working_dir: "/terraformroot"
    env_file: .env
volumes:
  public-volume:
  tmp-volume: