version: '3.7'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 2.7.0
        APP_PATH: /approot
        RAILS_ENV: development
        RACK_ENV: development
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/approot:cached
      - ./log:/approot/log:cached
      - public-volume:/approot/public
      - tmp-volume:/approot/tmp
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7.27
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
volumes:
  public-volume:
  tmp-volume:
  db-volume: