version: '3.7'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 2.7.0
        APP_PATH: /app
        RAILS_ENV: production
        RACK_ENV: production
    env_file: .env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app:cached
      - public-volume:/app/public
      - tmp-volume:/app/tmp
      - log-volume:/app/log
    tty: true
    stdin_open: true
  web:
    build:
      context: containers/nginx
    volumes:
      - public-volume:/app/public
      - tmp-volume:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-volume:
  tmp-volume:
  log-volume: