version: '3.7'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 2.7.0
        APP_PATH: /approot
        RAILS_ENV: production
        RACK_ENV: production
    env_file: .env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/approot:cached
      - ./log:/approot/log:cached
      - tmp-volume:/approot/tmp
      - log-volume:/approot/log
    tty: true
    stdin_open: true
  web:
    build:
      context: containers/nginx
    volumes:
      - public-volume:/approot/public
      - tmp-volume:/approot/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-volume:
  tmp-volume: